version: '3.8'

services:
  app:
    build: .
    container_name: url_shortener
    depends_on:
      - db
      - redis
    env_file:
      - .env  # Load environment variables
    ports:
      - "8080:8080"
    networks: 
      - app_network

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: URL_SHORTENER
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:

volumes:
  pg_data:
